Started by user anonymous
[workspace] $ mozmill -t /Users/adam/Documents/projects/main/bt/qaauto/windmill/spp/test_petshop
Traceback (most recent call last):
  File "/usr/local/bin/mozmill", line 8, in <module>
    load_entry_point('mozmill==1.2', 'console_scripts', 'mozmill')()
  File "/Users/adam/Documents/projects/mozmill/mozmill/__init__.py", line 392, in cli
    CLI().run()
  File "/Users/adam/Documents/projects/mozmill/mozmill/__init__.py", line 337, in run
    m.start(runner=runner, profile=runner.profile)
  File "/Users/adam/Documents/projects/mozmill/mozmill/__init__.py", line 104, in start
    self.back_channel, self.bridge = jsbridge.wait_and_create_network("127.0.0.1", self.jsbridge_port)
  File "/Library/Python/2.5/site-packages/jsbridge-2.0-py2.5.egg/jsbridge/__init__.py", line 69, in wait_and_create_network
    back_channel, bridge = create_network(host, port)
  File "/Library/Python/2.5/site-packages/jsbridge-2.0-py2.5.egg/jsbridge/network.py", line 267, in create_network
    back_channel = BackChannel(hostname, port)
  File "/Library/Python/2.5/site-packages/jsbridge-2.0-py2.5.egg/jsbridge/network.py", line 234, in __init__
    super(BackChannel, self).__init__(*args, **kwargs)
  File "/Library/Python/2.5/site-packages/jsbridge-2.0-py2.5.egg/jsbridge/network.py", line 166, in __init__
    self.connect(args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/asyncore.py", line 316, in connect
socket.error: (61, 'ECONNREFUSED')
Process leaked file descriptors. See http://hudson.gotdns.com/wiki/display/HUDSON/Spawning+processes+from+build for more information
Finished: UNSTABLE
